### PR TITLE
Disable collinearity tolerance

### LINKED ISSUE #39: "EdgeEvent - null triangle" from valid but not-quite-collinear points
It took a while for me to hit this in a real use case, but once I did it was surprisingly easy to boil down:

```
#include <poly2tri.h>

#include <numeric> 

int main(void)
{
  const double eps = 1e-15; // This gives EdgeEvent - null triangle
  // const double eps = 0;  // This (or negative eps) succeeds
    
  std::vector<p2t::Point> outer_boundary
    {{0,0},{0.5,eps},{1,0},{1,1},{0,1}};
    
  std::vector<p2t::Point *> api_shim(outer_boundary.size());
  std::iota(api_shim.begin(), api_shim.end(), outer_boundary.data());
  
  p2t::CDT cdt(api_shim);
    
  cdt.Triangulate();
  
  return 0;
}
```

A stack trace shows us dying 3 levels of `p2t::Sweep::EdgeEvent` deep, lines 114,151,120.  I'm afraid I don't really understand it, though.  The `EPSILON` tolerance in `Orient2D` puts us in the `o2 == COLLINEAR` block, which should be true for all practical purposes and should be the same block we reach in the `eps = 0` case, so why are we then failing for positive `eps`?

Hope you can help find a fix for this.  My user code that first tripped the error does adaptive refinement of boundary edges, which combined with FP roundoff means it's going to be generating not-quite-collinear points *all the time*.  I could try pushing those new boundary points outward a little bit so that they end up in the working convex-by-eps case rather than the failing concave-by-eps case, but that doesn't sound like a robust workaround.

### PR DESCRIPTION
**Pull request by roystgnr**
This is a naive way to fix #39 ... but at least for my cases, it works!

When I ran the poly2tri unit test suite, I got a failure ... but it turned out that the "failure" was that it stopped failing in a test that had previously been failing, so I'm going to call that a success instead and change the test to assert so.

I've added a new unit test too, with the original problem from #39 (rewritten to match the coding style of the other tests more closely), so even if it turns out that the Orient2d change isn't the best fix here, we can make sure subsequent fixes don't revert that progress.

With this in place my refinement code seems to be working, so I'll start conjuring up a bunch of test cases via that and see if I can trigger any other bugs that this fix missed or any previously-non-bug cases that this fix regressed.

### CODE REVIEW

File: poly2tri/common/utils.h [hunk 1]
```diff
@@ -68,7 +68,10 @@ Orientation Orient2d(const Point& pa, const Point& pb, const Point& pc)
   double detleft = (pa.x - pc.x) * (pb.y - pc.y);
   double detright = (pa.y - pc.y) * (pb.x - pc.x);
   double val = detleft - detright;
-  if (val > -EPSILON && val < EPSILON) {
+
+// Using a tolerance here fails on concave-by-subepsilon boundaries
+//   if (val > -EPSILON && val < EPSILON) {
+  if (val == 0) {
```
Comment (jhasse) [inline poly2tri/common/utils.h:74]: Maybe use `std::fpclassify(val) == FP_ZERO` to avoid the float comparision here?

Comment (jhasse) [reply poly2tri/common/utils.h]: Exactly :)

I think some compilers will warn on `equal_to`, too. But I'm not sure.

**Comment by roystgnr** [comment]
> I'll start conjuring up a bunch of test cases via that

I'm definitely still hitting a problem, if you want to wait on merging until I've had more time to investigate.  I think this one's more likely to be in my code than in yours, though.

**Comment by roystgnr** [comment]
That problem was a false alarm.  When I was cleaning up my own code's recent changes to strip out the "attempted workaround for poly2tri bug" parts, I accidentally also removed an in-progress fix for one of my own tolerance-related bugs because it looked similar.  Restoring that fix and getting rid of my own excessive tolerance fixed the problem for most cases, then switching to a more robust test in my code fixed the problem for every case I've tried, and I can now use this branch when refining triangulations into the millions-of-elements range (far past what my users need in 2D; their element count explodes when extruding meshes into 3D afterwards) without problems.

**Comment by roystgnr** [comment]
Is there anything else I can do to push for getting this merged?  I'm now developing using a forked branch downstream, and I was hoping to be able to switch that back to a hash on your master branch before users start relying on it.

I admit I'm not thrilled with this PR either; ideally solutions to hairy FP precision issues ought to be backed up via "mathematical proof in the docs", not "more passes in the test suite".  But "more passes in the test suite" is still a big step up from "fewer passes in the test suite".

**Comment by jhasse** [comment]
I agree.

Let's merge this and see if someone complains.

**Comment by jhasse** [comment]
Forgot to mention: Thank you very much! Especially for the detailed comments.

**Comment by roystgnr** [comment]
You're welcome!

> Let's merge this and see if someone complains.

There's probably a Russell conjugation here: "He breaks the code base; you add new features too hastily; I encourage collaborators to write more test coverage."

Tag me in any issues that come up if someone finds a regression?  The short-term solution might still be "tack on a revert commit" (you never rewrite history on master, right?) if a more longstanding user's needs conflict, but I'd definitely want to help make sure that the long-term solution was "find a fix that works for both issues" rather than "maintain a code fork" or "get stuck at an old commit".

**Comment by jhasse** [comment]
Yes, I would not force push. So if your hash on this repo will always be valid :)
